mater/urls.py
from django.urls import path
from . import views

app_name= 'mater'

urlpatterns = [
    path('', views.index, name='index'),
    path('predict_input/', views.predict_input, name='predict_input'),
    path('predict/', views.predict, name='predict'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mater.urls')),
]

mater/models.py
from django.db import models

# Create your models here.

mater/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView

# Create your views here.
from django.http import HttpResponse
from django.template import loader
#import pandas as pd
#from pandas import DataFrame

# 機械学習
#import sklearn
#import pickle
#from sklearn.ensemble import RandomForestRegressor
#from sklearn.model_selection import train_test_split

#import xgboost as xgb
#from sklearn.model_selection import cross_validate, KFold

class Predmater:
    def __init__(self):
        self.params = {}
    
    def load_model(self):
        filename = 'mater/files/model_RF.pickle'
        model = pickle.load(open(filename, 'rb'))
        return model
    
    def load_data(self, params):
        dat = {'hi':[params['hi']]
        ,'low':[params['low']]
        ,'rain':[params['rain']]
        ,'snow':[params['snow']]
        }
        df = DataFrame(dat)
        df = df.assign(hi = pd.to_numeric(df.hi))
        df = df.assign(low = pd.to_numeric(df.low))
        df = df.assign(rain = pd.to_numeric(df.rain))
        df = df.assign(snow = pd.to_numeric(df.snow))
        return df

def index(request):
    return render(request, 'mater/index.html')

def predict_input(request):
    return render(request, 'mater/index.html')

def predict(request):
    if request.method == 'POST':
        hi = request.POST.get('hi')
        low = request.POST.get('low')
        rain = request.POST.get('rain')
        snow = request.POST.get('snow')

        #param
        params = {'hi':hi, 'low':low, 'rain':rain, 'snow':snow}
        print(params)
        
        pred =Predmater()
        model =pred.load_model()
        df = pred.load_data(params)
        mater = model.predict(df)
        
        percent = mater * 100
        for x in percent: # リストを[]なしで表示
            print(x)
        cancelrate = (round(x,1))

        return render(request, 'mater/predict_out.html',     # 使用するテンプレート
                  {'mater': cancelrate })         # テンプレートに渡すデータ
    else:
        return HttpResponse('predict')

mater/templates/mater/index.html
{% load static %}
<html>
    <head>
        <title>キャンセル率予測</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/mater.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    </head>

    <body>  
        <form action="{% url 'mater:predict'  %}" method="post">
            {% csrf_token %}

            <h1>CancelRate Predict</h1>

            <div>
            <p>CancelRate Predictとは？</p>
            <p>天候情報をもとにキャンセル率を予測するAIです。</p>
            </div>

            <div>
            <label>
            最高気温
            <p><input type="number" name="hi" max="45" min="-35" value="0"></p>
            </label>
            </div>

            <div>
            <label>
            最低気温
            <p><input type="number" name="low" max="35" min="-45" value="0"></p>
            </label>
            </div>

            <div>
            <label>
            降水量
            <p><input type="number" name="rain" max="1000" min="0" value="0"></p>
            </label>
            </div>

            <div>
            <label>
            降雪量
            <p><input type="number" name="snow" max="1000" min="0" value="0"></p>
            </label>
            </div>

            <button type="submit" class="btn btn-success">予測</button>

        </form>
    </body>
</html>

mater/templates/mater/predict_out.html
{% load static %}
<html>
    <head>
        <title>予測結果</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/mater.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    </head>

    <body>
        <h1>Prediction Result</h1> 

        <div>
        <h2> {{mater}} % </h2>
        </div>
        
        <div>
        <a href="{% url 'mater:index' %}" class="btn btn-success">戻る</a>
        </div>
    </body>

</html>